version: '2'

services:
  ctfd:
    build: .
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://admin:Motiv0@176.96.231.11/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      # - .:/opt/CTFd:ro
      - .:/opt/CTFd
    # depends_on:
    #   - db
    networks:
        default:
        internal:

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./conf/nginx/http.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/certs/cert.crt:/etc/nginx/cert.crt:ro
      - ./conf/nginx/certs/cert.key:/etc/nginx/cert.key:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - ctfd
  
  # certbot:
  #     image: certbot/certbot:latest
  #     volumes:
  #       # - ./certbot/www/:/var/www/certbot/:rw
  #       # - ./certbot/logs/:/var/log/letsencrypt/:rw
  #       - ./certbot/conf:/etc/letsencrypt
  #       - ./certbot/www:/var/www/certbot
  #     command: certonly --webroot -w /var/www/certbot --force-renewal --email test@gmail.com -d ctephec.codes --agree-tos

  # db:
  #   image: mariadb:10.4.12
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=Motiv0
  #     - MYSQL_USER=admin
  #     - MYSQL_PASSWORD=Motiv0
  #     - MYSQL_DATABASE=ctfd
  #   volumes:
  #     - .data/mysql:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   networks:
  #       default:
  #       internal:
  #   # This command is required to set important mariadb defaults
  #   command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
        internal:

networks:
    default:
    internal:
        internal: true
